### ISSUE TITLE
iOS lookup only checks US store

### ISSUE THREAD

**Issue by SEGVeenstra** [mateusfccp/update_available#10]
When an iOS app is not available in the US store it will return `UnknownAvailability`.

Our app is only available from the Dutch (NL) store but the plugin checks only the US store (`https://itunes.apple.com/lookup`).

For the plugin to work for us, it should be looking at the Dutch store (`https://itunes.apple.com/nl/lookup`).

**Comment by mateusfccp** [comment]
Hello, @SEGVeenstra . Thanks for opening this issue!

I used to have a app in production in Brazil (where I am from) and we used this same lookup URL, so I was not aware that it may not work in some countries...

I am working on a update to bump the dependencies, so I may work on this issue in this same update.

**Comment by SEGVeenstra** [comment]
Any idea on how this can be solved?

Would it be an option to check the device's region or something and target the store for this region?

**Comment by mateusfccp** [comment]
> Any idea on how this can be solved?
> 
> Would it be an option to check the device's region or something and target the store for this region?

I though on this, but I am afraid this may be not the ideal solution, for some reasons:

* This does not seem to be a reliable solution, as we are going to have to map locations to URLs which can be quite error-prone. Also, there are times that the device does not give the exact location...
* To do this, we would have to ask permission to the device to read its location.
    * What happens if the user does not allow? We will simply return `UnknownAvailability`?
    * We are going to add one more dependency to the package, and it will go a little out of scope of the package regarding objective and simplicity.

I think that the more straightforward solution is to expose this to the API as a parameter or something like this...

WDYT?

**Comment by SEGVeenstra** [comment]
> I think that the more straightforward solution is to expose this to the API as a parameter or something like this...

Thought about this solution as well. Although it would be nice if it could be automatically determined.

> To do this, we would have to ask permission to the device to read its location.
I did not mean to read the current location. I thought iOS users configure a region on their phone.

**Comment by SEGVeenstra** [comment]
> I thought iOS users configure a region on their phone.
I'm not sure if this is even accessible information though..

**Comment by mateusfccp** [comment]
> I'm not sure if this is even accessible information though..

Looking for it, I didn't find much information except for this [StackOverflow question](https://stackoverflow.com/questions/12673351/determine-country-associated-with-apple-id-logged-into-the-ios-device), which answer is "you can't".

**Comment by SEGVeenstra** [comment]
> > I'm not sure if this is even accessible information though..
> 
> Looking for it, I didn't find much information except for this [StackOverflow question](https://stackoverflow.com/questions/12673351/determine-country-associated-with-apple-id-logged-into-the-ios-device), which answer is "you can't".
> 

Hmm, to bad...
Then maybe your parameter suggestion is best. Then the package user can figure out a way to get that information.

**Comment by mateusfccp** [comment]
@SEGVeenstra As soon as we merge #11 I will publish a new beta version, could you help me testing this feature?

**Comment by SEGVeenstra** [comment]
Did you find somewhere what the available regions are?
I know the lookup is a 'work around' because iOS doesn't offer a legit API, but I think it would help consumers of the package if they know what valid regions would be.

**Comment by rkfcccccc** [comment]
@SEGVeenstra

According to my observations, the available regions comply with the ISO 3166-1 alpha-2 standard. I mentioned this in the README.

**Comment by mateusfccp** [comment]
@SEGVeenstra Sorry to bother you, but did you manage to solve your problem using the development version?

**Comment by mateusfccp** [comment]
As I did not get any response from OP, I am considering this issue solved by #11, which was released with version `2.2.0`. Thus, I am closing this. Feel free to reopen/comment if you feel like this hasn't been properly solved.

**Comment by SEGVeenstra** [comment]
Sorry, i completely forgot about this since I was removed of the project that required it.

**Comment by mateusfccp** [comment]
No problem, @SEGVeenstra. Thank you for the support anyway!
