### ISSUE TITLE
Support package_info_plus 3

### ISSUE THREAD

**Issue by kuhnroyal** [mateusfccp/update_available#17]
It would be great if the package could support the latest `package_info_plus` which also added the `installerStore` information in 2.0.0.

This could maybe help `update_available` to figure out where the app was installed from.

**Comment by mateusfccp** [comment]
Thanks for your input!

I am going to have a look at this (and the other issues) when I go on vacation on this December.

**Comment by mateusfccp** [comment]
The support for `package_info_plus: ^3.0.0` has been provided in the new `2.2.0` release.

I am going to close this issue as solved.

Regarding using the information about where the app was installed from, if you feel like this information is somehow important to the package, could you please elaborate on this in a new issue? Thanks!
