### ISSUE TITLE
Changing the update procedures generated a new bug

### ISSUE THREAD

**Issue by paulobreim** [mateusfccp/update_available#24]
For some reason, when we use the update routine, instead of going to the playstore update page, a page is being presented, with a question: Install in other locations.
See the screen below (in Portuguese) (instalar em outros locais).

![image](https://user-images.githubusercontent.com/381594/222933438-48ef8a6e-f04d-48ac-9e45-4dea70a0225f.png)
Any idea?

**Comment by mateusfccp** [comment]
Hello, @paulobreim.

What do you mean with "update routine"? The API only provides methods to check if there's updates available, but does not provide any method to update the app.

Can you provide an example?

Thanks!

**Comment by paulobreim** [comment]
Hummm you are right. After received that there are a new version, I launch a URL like:
https://play.google.com/store/apps/details?id=aeroescuta.com.br
This command showed to update, but now somethings change there and not work anymore.

I will search to see what Google change.

Tks
paulo
