### ISSUE TITLE
Update Android app-update dependency

### ISSUE THREAD

**Issue by kuhnroyal** [mateusfccp/update_available#42]
I received this Google Play warning just now:

```
com.google.android.play:app-update has added this note for app-update:2.0.1:

Update your Play In-App Updates Maven dependency to an Android 14 compatible version! Your current Play In-App Updates library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#java-kotlin-in-app-update
```

**Comment by mateusfccp** [comment]
I'm failing to understand why you have `2.0.1` installed when `build.gradle` requires `2.1.0`, which is compatible with Android 14[^1].

https://github.com/mateusfccp/update_available/blob/ae9bdfa376df5e2de9749e82dddbde9096c8dc88/update_available_android/android/build.gradle#L49

Also, there's no reference to the old Play Core libraries, not in the gradle file nor in the kotlin source code[^2].

Those are the only possible causes I could find.

Do you have any idea?

[^1]: https://developer.android.com/reference/com/google/android/play/core/release-notes-in_app_updates#2-1-0
[^2]: https://developer.android.com/guide/playcore#playcore-migration

**Comment by kuhnroyal** [comment]
Hmm, maybe my 2 production apps are too old, will check tomorrow.

**Comment by kuhnroyal** [comment]
Yea, the production apps are still using version `3.0.1`.
My bad, sorry for the noise.
