### ISSUE TITLE
iTunes lookup api returns older version

### ISSUE THREAD

**Issue by nemscep** [mateusfccp/update_available#47]
It seems that some caching occurs on iTunes Api side as even though update is available on AppStore, lookup api returns older version thus returning `UpdateNotAvailable` as a result. 

Now I have investigated a bit and found that caching is taking part of this url execution (24h) and thus any successive calls will just return cached values aka old version in my case for some reason. 

Way to test and verify that caching takes place, if I append &ver=1 randomly to the url (https://itunes.apple.com/lookup?bundleId=some.bundle.id&ver=1) new fresh value is returned immediately 🤷 

Now I have no idea how to deal with this as on one hand adding lets say timestamp as a parameter will solve everything, but on the other iTunes might deem this as throttle or ddos potentially since now every call should return non-cached values. 

Any ideas, remarks would be greatly appreciated! 🙏

**Comment by nemscep** [comment]
@mateusfccp Uh, definitely saw that I am not. 
Now question, will after 24h cache be invalidated within the lib or must I update the lib in order for this to start reset?

**Comment by mateusfccp** [comment]
@nemscep I never tested it, but as it makes the request every time it tries to evaluate if it has an update, it should work after the iTunes cache is invalidated.

But I would still recommend updating the package version to get the cache buster feature.

**Comment by nemscep** [comment]
@mateusfccp I just hope that currently released app recovers from this caching soon 😬 
Next update of the app I upgrade the lib version.
Thanks for your answers!

**Comment by mateusfccp** [comment]
I'm going to close this issue.

Feel free to reopen it if you think there's something else we need to do.
