### ISSUE TITLE
Update dependencies to their latest null safe version

### ISSUE THREAD

**Issue by ashishbeck** [mateusfccp/update_available#5]
Hello, with the release of Flutter 2.0, the packages that this depends on need updating.
I have had conflicts with http and platform_interface so far. Could you please update the packages?
I could look into the code and create a PR if needed.

**Comment by mateusfccp** [comment]
@ashishbeck Thanks for contacting me!

I made a new publication `2.0.0-nullsafety`. As I am not currently using Flutter 2.0 in production I don't have a proper setup to test this, but the code is properly migrated and all tests has passed.

Would you please try it for me? If you deem it working I will gladly publish it as stable (`2.0.0`).

**Comment by ashishbeck** [comment]
The package is compiling and building fine. There aren't any issues. I can't seem to check for updates locally in android however. I think it's because I need to install from Google Play for the APIs to kick in. Regardless, the `notAvailable` function does work and I think it is okay to be published.

**Comment by mateusfccp** [comment]
Thanks, @ashishbeck. Published `2.0.0` as stable. If you find any issue, please report it.
