### ISSUE TITLE
test on ios via testflight does not work?

### ISSUE THREAD

**Issue by weldonsouza** [mateusfccp/update_available#6]
I performed the test through testflight, but it didn't work, the result is only possible if you publish it in the apple store?

**Comment by weldonsouza** [comment]
Thanks for the answer and good job on your plugin, unfortunately I don't know, so I asked the question.

I found this documentation from appstore connect api
https://developer.apple.com/documentation/appstoreconnectapi/apps.
I'm still reading about how it works, probably you should have some way to adapt it to your plugin.
I hope it helps.

**Comment by mateusfccp** [comment]
@weldonsouza thanks, I am going to give a look too, maybe it is a valid solution for our problem!
